version: '3.7'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - db_connection
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos

  mysql:
    image: mysql:5.7
    networks:
      - db_connection
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: todos
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

# Networking
networks: 
  db_connection:
    ipam: 
      driver: default
      config:
        - subnet: 172.16.238.0/24
# Volumes
volumes:
  mysql-database-data-volume: